### ISSUE TITLE
Feature Request:  Colored Health bar when party member has cleansable debuff

### ISSUE THREAD

**Issue by connorwilsongroark** [i2ichardt/HealersMate#1]
Hey man, love the addon.  Would it be possible to have the health bar change color when the party member has a debuff that can be cleansed in a future update?

**Comment by i2ichardt** [comment]
I'm working on an update that's almost finished and will probably be out this weekend. Im mainly just bug testing at the moment. It adds mana/energy/rage bars for the players along with handling when druids change forms, and optional scrolling combat text for when someone 
I'm working on an update that's almost finished and will probably be out this weekend. Im mainly just bug testing at the moment. It adds mana/energy/rage bars for the players along with handling when druids change forms, and optional scrolling combat text for when someone gets hit and/or heals.

The version of wow client that turtle wow uses only shows the the texture path of the buff icon, stacksize, and if it is a buff or debuff not the type

I think someone manually made a database file for the missing spell information I could steal to reference based on the buff texturepath but I don't know how reliable it would be due to blizzard reusing the same icon for more than one thing so you could get false positives. There would be no way to prevent False positives which is why I haven't looked into it.

Of course I could be wrong since I'm just a hobbiest, that's my current understanding.

**Comment by i2ichardt** [comment]
Updated.

**Comment by OldManAlpha** [comment]
This feature is now present in 2.0.0 Alpha.
